### ISSUE TITLE
Can't combine enchanted crossbows (and possibly other items)

### ISSUE THREAD

**Issue by nordlead2005** [knokko/Custom-Items#1]
**Issue**
When you try to take a combined crossbow out of an anvil, you are kicked out of the anvil and the items are not combined and no XP is consumed.

I had the same issue with another item, but don't remember which.

**How to reproduce**
1) Give yourself 2 crossbows
2) Enchant 1 with Unbreaking 3, the other with Quickcharge 3
3) Put both crossbows in an anvil (make sure you have enough xp)
4) Select the output crossbow

**Versions:**
Custom Items 5.7
Knokko Core 1.14 4

I disabled various plugins that I had recently installed, and I can successfully reproduce this bug only when Custom Items is enabled.

**Comment by nordlead2005** [comment]
I just saw in the comments on the bukkit page that items past 1.12 aren't supported, so that is probably the issue. I don't know how minecraft or this plugin is coded, but it would be nice if the plugin did not interfere with anvil actions it wasn't aware of and it should let the native minecraft code reject improper anvil actions.

**Comment by knokko** [comment]
Sorry for the late reply, I wasn't notified for some reason.
I am currently working on the version that will add proper support for later items, so there is a good chance this will be solved in the next version.
If things go well, it will be published next week.

**Comment by nordlead2005** [comment]
No problem. I don't have a bukkit account and figured you'd see this eventually and then noticed some of the comments and realized this was sort of known about.

**Comment by TechWizzart** [comment]
The bug has been fixed, which will be released in the new version and should prevent this problem in the future when Minecraft updates and the plugin has not updated yet.

**Comment by knokko** [comment]
The new version (5.8) has been released.
